import { MockErpState } from '../models/mock-erp-state.model';
import { WorkCenterDocument } from '../models/work-center.model';
import { WorkOrderDocument } from '../models/work-order.model';

/**
 * Seed data for the in-memory mock ERP.
 *
 * Kept separate from the service so the service contains only behaviour, and so
 * a real backend can drop in by swapping how the initial {@link MockErpState}
 * is produced.
 */
const centers: WorkCenterDocument[] = [
  { docId: '1', docType: 'WorkCenter', data: { name: 'Genesis Hardware' } },
  { docId: '2', docType: 'WorkCenter', data: { name: 'Rodriques Electrics' } },
  { docId: '3', docType: 'WorkCenter', data: { name: 'Konsulting Inc' } },
  { docId: '4', docType: 'WorkCenter', data: { name: 'McMarrow Distribution' } },
  { docId: '5', docType: 'WorkCenter', data: { name: 'Spartan Manufacturing' } },
  { docId: '6', docType: 'WorkCenter', data: { name: 'Atlas Fabrication' } },
  { docId: '7', docType: 'WorkCenter', data: { name: 'Vertex Assembly' } },
  { docId: '8', docType: 'WorkCenter', data: { name: 'Pinnacle Tooling' } },
  { docId: '9', docType: 'WorkCenter', data: { name: 'Northgate Foundry' } },
];

const orders: WorkOrderDocument[] = [
  {
    docId: '1',
    docType: 'WorkOrder',
    data: {
      name: 'Frame assembly',
      workCenterId: '1',
      status: 'complete',
      startDate: '2026-03-24',
      endDate: '2026-03-26',
    },
  },
  {
    docId: '2',
    docType: 'WorkOrder',
    data: {
      name: 'Wiring harness build',
      workCenterId: '1',
      status: 'complete',
      startDate: '2026-04-04',
      endDate: '2026-04-15',
    },
  },
  {
    docId: '3',
    docType: 'WorkOrder',
    data: {
      name: 'QA sample inspection',
      workCenterId: '1',
      status: 'complete',
      startDate: '2026-04-30',
      endDate: '2026-05-04',
    },
  },
  {
    docId: '4',
    docType: 'WorkOrder',
    data: {
      name: 'Tooling retrofit',
      workCenterId: '1',
      status: 'in-progress',
      startDate: '2026-06-03',
      endDate: '2026-06-09',
    },
  },
  {
    docId: '5',
    docType: 'WorkOrder',
    data: {
      name: 'Pallet restock',
      workCenterId: '1',
      status: 'open',
      startDate: '2026-06-27',
      endDate: '2026-07-03',
    },
  },
  {
    docId: '6',
    docType: 'WorkOrder',
    data: {
      name: 'Line recommission',
      workCenterId: '1',
      status: 'open',
      startDate: '2026-07-19',
      endDate: '2026-07-23',
    },
  },
  {
    docId: '7',
    docType: 'WorkOrder',
    data: {
      name: 'Circuit board batch',
      workCenterId: '1',
      status: 'open',
      startDate: '2026-09-01',
      endDate: '2026-09-04',
    },
  },
  {
    docId: '8',
    docType: 'WorkOrder',
    data: {
      name: 'Compliance audit',
      workCenterId: '2',
      status: 'complete',
      startDate: '2026-03-22',
      endDate: '2026-04-02',
    },
  },
  {
    docId: '9',
    docType: 'WorkOrder',
    data: {
      name: 'Motor calibration',
      workCenterId: '2',
      status: 'complete',
      startDate: '2026-04-26',
      endDate: '2026-05-05',
    },
  },
  {
    docId: '10',
    docType: 'WorkOrder',
    data: {
      name: 'Firmware flash',
      workCenterId: '2',
      status: 'complete',
      startDate: '2026-05-18',
      endDate: '2026-05-28',
    },
  },
  {
    docId: '11',
    docType: 'WorkOrder',
    data: {
      name: 'Daily safety check',
      workCenterId: '2',
      status: 'open',
      startDate: '2026-06-16',
      endDate: '2026-06-19',
    },
  },
  {
    docId: '12',
    docType: 'WorkOrder',
    data: {
      name: 'Conveyor overhaul',
      workCenterId: '2',
      status: 'open',
      startDate: '2026-07-27',
      endDate: '2026-08-04',
    },
  },
  {
    docId: '13',
    docType: 'WorkOrder',
    data: {
      name: 'Shift handover',
      workCenterId: '2',
      status: 'open',
      startDate: '2026-08-11',
      endDate: '2026-08-17',
    },
  },
  {
    docId: '14',
    docType: 'WorkOrder',
    data: {
      name: 'Coolant leak repair',
      workCenterId: '3',
      status: 'complete',
      startDate: '2026-03-26',
      endDate: '2026-03-30',
    },
  },
  {
    docId: '15',
    docType: 'WorkOrder',
    data: {
      name: 'Packaging changeover',
      workCenterId: '3',
      status: 'complete',
      startDate: '2026-04-15',
      endDate: '2026-04-26',
    },
  },
  {
    docId: '16',
    docType: 'WorkOrder',
    data: {
      name: 'Final shipment prep',
      workCenterId: '3',
      status: 'complete',
      startDate: '2026-05-09',
      endDate: '2026-05-10',
    },
  },
  {
    docId: '17',
    docType: 'WorkOrder',
    data: {
      name: 'Gearbox rebuild',
      workCenterId: '3',
      status: 'blocked',
      startDate: '2026-06-09',
      endDate: '2026-06-12',
    },
  },
  {
    docId: '18',
    docType: 'WorkOrder',
    data: {
      name: 'Sensor recalibration',
      workCenterId: '3',
      status: 'open',
      startDate: '2026-06-26',
      endDate: '2026-07-07',
    },
  },
  {
    docId: '19',
    docType: 'WorkOrder',
    data: {
      name: 'Weld inspection',
      workCenterId: '3',
      status: 'open',
      startDate: '2026-07-29',
      endDate: '2026-08-05',
    },
  },
  {
    docId: '20',
    docType: 'WorkOrder',
    data: {
      name: 'Paint booth cycle',
      workCenterId: '3',
      status: 'open',
      startDate: '2026-09-01',
      endDate: '2026-09-03',
    },
  },
  {
    docId: '21',
    docType: 'WorkOrder',
    data: {
      name: 'Bearing replacement',
      workCenterId: '4',
      status: 'complete',
      startDate: '2026-03-27',
      endDate: '2026-04-02',
    },
  },
  {
    docId: '22',
    docType: 'WorkOrder',
    data: {
      name: 'Hydraulic flush',
      workCenterId: '4',
      status: 'complete',
      startDate: '2026-04-06',
      endDate: '2026-04-09',
    },
  },
  {
    docId: '23',
    docType: 'WorkOrder',
    data: {
      name: 'Spindle alignment',
      workCenterId: '4',
      status: 'complete',
      startDate: '2026-05-12',
      endDate: '2026-05-23',
    },
  },
  {
    docId: '24',
    docType: 'WorkOrder',
    data: {
      name: 'Material intake',
      workCenterId: '4',
      status: 'in-progress',
      startDate: '2026-05-29',
      endDate: '2026-06-09',
    },
  },
  {
    docId: '25',
    docType: 'WorkOrder',
    data: {
      name: 'Die change',
      workCenterId: '4',
      status: 'open',
      startDate: '2026-07-05',
      endDate: '2026-07-07',
    },
  },
  {
    docId: '26',
    docType: 'WorkOrder',
    data: {
      name: 'Pressure test',
      workCenterId: '4',
      status: 'open',
      startDate: '2026-07-22',
      endDate: '2026-07-24',
    },
  },
  {
    docId: '27',
    docType: 'WorkOrder',
    data: {
      name: 'Lubrication round',
      workCenterId: '4',
      status: 'open',
      startDate: '2026-08-20',
      endDate: '2026-08-31',
    },
  },
  {
    docId: '28',
    docType: 'WorkOrder',
    data: {
      name: 'Cable routing',
      workCenterId: '5',
      status: 'complete',
      startDate: '2026-03-13',
      endDate: '2026-03-15',
    },
  },
  {
    docId: '29',
    docType: 'WorkOrder',
    data: {
      name: 'Panel fit-up',
      workCenterId: '5',
      status: 'complete',
      startDate: '2026-04-05',
      endDate: '2026-04-10',
    },
  },
  {
    docId: '30',
    docType: 'WorkOrder',
    data: {
      name: 'Coating cure',
      workCenterId: '5',
      status: 'complete',
      startDate: '2026-05-08',
      endDate: '2026-05-12',
    },
  },
  {
    docId: '31',
    docType: 'WorkOrder',
    data: {
      name: 'Robot teach pass',
      workCenterId: '5',
      status: 'in-progress',
      startDate: '2026-06-02',
      endDate: '2026-06-08',
    },
  },
  {
    docId: '32',
    docType: 'WorkOrder',
    data: {
      name: 'Fixture setup',
      workCenterId: '5',
      status: 'open',
      startDate: '2026-06-23',
      endDate: '2026-06-24',
    },
  },
  {
    docId: '33',
    docType: 'WorkOrder',
    data: {
      name: 'Batch teardown',
      workCenterId: '5',
      status: 'open',
      startDate: '2026-07-31',
      endDate: '2026-08-09',
    },
  },
  {
    docId: '34',
    docType: 'WorkOrder',
    data: {
      name: 'Quality hold review',
      workCenterId: '5',
      status: 'open',
      startDate: '2026-08-21',
      endDate: '2026-08-24',
    },
  },
  {
    docId: '35',
    docType: 'WorkOrder',
    data: {
      name: 'Preventive service',
      workCenterId: '6',
      status: 'complete',
      startDate: '2026-03-21',
      endDate: '2026-04-01',
    },
  },
  {
    docId: '36',
    docType: 'WorkOrder',
    data: {
      name: 'Component sorting',
      workCenterId: '6',
      status: 'complete',
      startDate: '2026-04-12',
      endDate: '2026-04-21',
    },
  },
  {
    docId: '37',
    docType: 'WorkOrder',
    data: {
      name: 'Stock count',
      workCenterId: '6',
      status: 'complete',
      startDate: '2026-05-13',
      endDate: '2026-05-18',
    },
  },
  {
    docId: '38',
    docType: 'WorkOrder',
    data: {
      name: 'Heat treat run',
      workCenterId: '6',
      status: 'open',
      startDate: '2026-06-23',
      endDate: '2026-07-03',
    },
  },
  {
    docId: '39',
    docType: 'WorkOrder',
    data: {
      name: 'Surface finish',
      workCenterId: '6',
      status: 'open',
      startDate: '2026-07-28',
      endDate: '2026-08-01',
    },
  },
  {
    docId: '40',
    docType: 'WorkOrder',
    data: {
      name: 'Tool sharpening',
      workCenterId: '6',
      status: 'open',
      startDate: '2026-08-17',
      endDate: '2026-08-27',
    },
  },
  {
    docId: '41',
    docType: 'WorkOrder',
    data: {
      name: 'Belt tensioning',
      workCenterId: '7',
      status: 'complete',
      startDate: '2026-03-09',
      endDate: '2026-03-16',
    },
  },
  {
    docId: '42',
    docType: 'WorkOrder',
    data: {
      name: 'Valve overhaul',
      workCenterId: '7',
      status: 'complete',
      startDate: '2026-04-03',
      endDate: '2026-04-08',
    },
  },
  {
    docId: '43',
    docType: 'WorkOrder',
    data: {
      name: 'Pump priming',
      workCenterId: '7',
      status: 'complete',
      startDate: '2026-05-11',
      endDate: '2026-05-12',
    },
  },
  {
    docId: '44',
    docType: 'WorkOrder',
    data: {
      name: 'Filter swap',
      workCenterId: '7',
      status: 'in-progress',
      startDate: '2026-06-02',
      endDate: '2026-06-13',
    },
  },
  {
    docId: '45',
    docType: 'WorkOrder',
    data: {
      name: 'Drive test',
      workCenterId: '7',
      status: 'open',
      startDate: '2026-07-04',
      endDate: '2026-07-07',
    },
  },
  {
    docId: '46',
    docType: 'WorkOrder',
    data: {
      name: 'Enclosure assembly',
      workCenterId: '7',
      status: 'open',
      startDate: '2026-07-30',
      endDate: '2026-08-03',
    },
  },
  {
    docId: '47',
    docType: 'WorkOrder',
    data: {
      name: 'Label run',
      workCenterId: '7',
      status: 'blocked',
      startDate: '2026-08-18',
      endDate: '2026-08-25',
    },
  },
  {
    docId: '48',
    docType: 'WorkOrder',
    data: {
      name: 'Crate build',
      workCenterId: '8',
      status: 'complete',
      startDate: '2026-03-25',
      endDate: '2026-03-30',
    },
  },
  {
    docId: '49',
    docType: 'WorkOrder',
    data: {
      name: 'Frame assembly',
      workCenterId: '8',
      status: 'complete',
      startDate: '2026-04-19',
      endDate: '2026-04-20',
    },
  },
  {
    docId: '50',
    docType: 'WorkOrder',
    data: {
      name: 'Wiring harness build',
      workCenterId: '8',
      status: 'complete',
      startDate: '2026-05-08',
      endDate: '2026-05-17',
    },
  },
  {
    docId: '51',
    docType: 'WorkOrder',
    data: {
      name: 'QA sample inspection',
      workCenterId: '8',
      status: 'open',
      startDate: '2026-06-29',
      endDate: '2026-07-06',
    },
  },
  {
    docId: '52',
    docType: 'WorkOrder',
    data: {
      name: 'Tooling retrofit',
      workCenterId: '8',
      status: 'open',
      startDate: '2026-07-13',
      endDate: '2026-07-22',
    },
  },
  {
    docId: '53',
    docType: 'WorkOrder',
    data: {
      name: 'Pallet restock',
      workCenterId: '8',
      status: 'open',
      startDate: '2026-08-10',
      endDate: '2026-08-19',
    },
  },
  {
    docId: '54',
    docType: 'WorkOrder',
    data: {
      name: 'Line recommission',
      workCenterId: '9',
      status: 'complete',
      startDate: '2026-03-23',
      endDate: '2026-03-28',
    },
  },
  {
    docId: '55',
    docType: 'WorkOrder',
    data: {
      name: 'Circuit board batch',
      workCenterId: '9',
      status: 'complete',
      startDate: '2026-04-25',
      endDate: '2026-04-27',
    },
  },
  {
    docId: '56',
    docType: 'WorkOrder',
    data: {
      name: 'Compliance audit',
      workCenterId: '9',
      status: 'complete',
      startDate: '2026-05-04',
      endDate: '2026-05-11',
    },
  },
  {
    docId: '57',
    docType: 'WorkOrder',
    data: {
      name: 'Motor calibration',
      workCenterId: '9',
      status: 'complete',
      startDate: '2026-06-01',
      endDate: '2026-06-02',
    },
  },
  {
    docId: '58',
    docType: 'WorkOrder',
    data: {
      name: 'Firmware flash',
      workCenterId: '9',
      status: 'open',
      startDate: '2026-06-28',
      endDate: '2026-07-05',
    },
  },
  {
    docId: '59',
    docType: 'WorkOrder',
    data: {
      name: 'Daily safety check',
      workCenterId: '9',
      status: 'open',
      startDate: '2026-08-02',
      endDate: '2026-08-09',
    },
  },
  {
    docId: '60',
    docType: 'WorkOrder',
    data: {
      name: 'Conveyor overhaul',
      workCenterId: '9',
      status: 'open',
      startDate: '2026-08-20',
      endDate: '2026-08-24',
    },
  },
  {
    docId: '61',
    docType: 'WorkOrder',
    data: {
      name: 'Shift handover',
      workCenterId: '10',
      status: 'complete',
      startDate: '2026-03-24',
      endDate: '2026-03-30',
    },
  },
  {
    docId: '62',
    docType: 'WorkOrder',
    data: {
      name: 'Coolant leak repair',
      workCenterId: '10',
      status: 'complete',
      startDate: '2026-04-25',
      endDate: '2026-05-05',
    },
  },
  {
    docId: '63',
    docType: 'WorkOrder',
    data: {
      name: 'Packaging changeover',
      workCenterId: '10',
      status: 'complete',
      startDate: '2026-05-08',
      endDate: '2026-05-11',
    },
  },
  {
    docId: '64',
    docType: 'WorkOrder',
    data: {
      name: 'Final shipment prep',
      workCenterId: '10',
      status: 'open',
      startDate: '2026-06-15',
      endDate: '2026-06-25',
    },
  },
  {
    docId: '65',
    docType: 'WorkOrder',
    data: {
      name: 'Gearbox rebuild',
      workCenterId: '10',
      status: 'blocked',
      startDate: '2026-07-19',
      endDate: '2026-07-26',
    },
  },
  {
    docId: '66',
    docType: 'WorkOrder',
    data: {
      name: 'Sensor recalibration',
      workCenterId: '10',
      status: 'open',
      startDate: '2026-08-30',
      endDate: '2026-09-02',
    },
  },
  {
    docId: '67',
    docType: 'WorkOrder',
    data: {
      name: 'Weld inspection',
      workCenterId: '11',
      status: 'complete',
      startDate: '2026-03-27',
      endDate: '2026-03-30',
    },
  },
  {
    docId: '68',
    docType: 'WorkOrder',
    data: {
      name: 'Paint booth cycle',
      workCenterId: '11',
      status: 'complete',
      startDate: '2026-04-13',
      endDate: '2026-04-24',
    },
  },
  {
    docId: '69',
    docType: 'WorkOrder',
    data: {
      name: 'Bearing replacement',
      workCenterId: '11',
      status: 'complete',
      startDate: '2026-05-03',
      endDate: '2026-05-10',
    },
  },
  {
    docId: '70',
    docType: 'WorkOrder',
    data: {
      name: 'Hydraulic flush',
      workCenterId: '11',
      status: 'complete',
      startDate: '2026-05-27',
      endDate: '2026-06-02',
    },
  },
  {
    docId: '71',
    docType: 'WorkOrder',
    data: {
      name: 'Spindle alignment',
      workCenterId: '11',
      status: 'blocked',
      startDate: '2026-07-01',
      endDate: '2026-07-10',
    },
  },
  {
    docId: '72',
    docType: 'WorkOrder',
    data: {
      name: 'Material intake',
      workCenterId: '11',
      status: 'open',
      startDate: '2026-08-09',
      endDate: '2026-08-11',
    },
  },
  {
    docId: '73',
    docType: 'WorkOrder',
    data: {
      name: 'Die change',
      workCenterId: '11',
      status: 'open',
      startDate: '2026-08-24',
      endDate: '2026-08-25',
    },
  },
  {
    docId: '74',
    docType: 'WorkOrder',
    data: {
      name: 'Pressure test',
      workCenterId: '12',
      status: 'complete',
      startDate: '2026-03-13',
      endDate: '2026-03-24',
    },
  },
  {
    docId: '75',
    docType: 'WorkOrder',
    data: {
      name: 'Lubrication round',
      workCenterId: '12',
      status: 'complete',
      startDate: '2026-04-20',
      endDate: '2026-04-27',
    },
  },
  {
    docId: '76',
    docType: 'WorkOrder',
    data: {
      name: 'Cable routing',
      workCenterId: '12',
      status: 'complete',
      startDate: '2026-05-21',
      endDate: '2026-05-22',
    },
  },
  {
    docId: '77',
    docType: 'WorkOrder',
    data: {
      name: 'Panel fit-up',
      workCenterId: '12',
      status: 'open',
      startDate: '2026-06-12',
      endDate: '2026-06-16',
    },
  },
  {
    docId: '78',
    docType: 'WorkOrder',
    data: {
      name: 'Coating cure',
      workCenterId: '12',
      status: 'open',
      startDate: '2026-07-31',
      endDate: '2026-08-03',
    },
  },
  {
    docId: '79',
    docType: 'WorkOrder',
    data: {
      name: 'Robot teach pass',
      workCenterId: '12',
      status: 'open',
      startDate: '2026-08-11',
      endDate: '2026-08-18',
    },
  },
  {
    docId: '80',
    docType: 'WorkOrder',
    data: {
      name: 'Fixture setup',
      workCenterId: '13',
      status: 'complete',
      startDate: '2026-03-10',
      endDate: '2026-03-14',
    },
  },
  {
    docId: '81',
    docType: 'WorkOrder',
    data: {
      name: 'Batch teardown',
      workCenterId: '13',
      status: 'complete',
      startDate: '2026-04-12',
      endDate: '2026-04-18',
    },
  },
  {
    docId: '82',
    docType: 'WorkOrder',
    data: {
      name: 'Quality hold review',
      workCenterId: '13',
      status: 'complete',
      startDate: '2026-04-30',
      endDate: '2026-05-10',
    },
  },
  {
    docId: '83',
    docType: 'WorkOrder',
    data: {
      name: 'Preventive service',
      workCenterId: '13',
      status: 'in-progress',
      startDate: '2026-06-08',
      endDate: '2026-06-12',
    },
  },
  {
    docId: '84',
    docType: 'WorkOrder',
    data: {
      name: 'Component sorting',
      workCenterId: '13',
      status: 'blocked',
      startDate: '2026-07-03',
      endDate: '2026-07-07',
    },
  },
  {
    docId: '85',
    docType: 'WorkOrder',
    data: {
      name: 'Stock count',
      workCenterId: '13',
      status: 'open',
      startDate: '2026-07-30',
      endDate: '2026-08-05',
    },
  },
  {
    docId: '86',
    docType: 'WorkOrder',
    data: {
      name: 'Heat treat run',
      workCenterId: '13',
      status: 'open',
      startDate: '2026-08-23',
      endDate: '2026-08-31',
    },
  },
  {
    docId: '87',
    docType: 'WorkOrder',
    data: {
      name: 'Surface finish',
      workCenterId: '14',
      status: 'complete',
      startDate: '2026-03-28',
      endDate: '2026-04-01',
    },
  },
  {
    docId: '88',
    docType: 'WorkOrder',
    data: {
      name: 'Tool sharpening',
      workCenterId: '14',
      status: 'complete',
      startDate: '2026-04-12',
      endDate: '2026-04-13',
    },
  },
  {
    docId: '89',
    docType: 'WorkOrder',
    data: {
      name: 'Belt tensioning',
      workCenterId: '14',
      status: 'complete',
      startDate: '2026-05-20',
      endDate: '2026-05-27',
    },
  },
  {
    docId: '90',
    docType: 'WorkOrder',
    data: {
      name: 'Valve overhaul',
      workCenterId: '14',
      status: 'open',
      startDate: '2026-06-16',
      endDate: '2026-06-27',
    },
  },
  {
    docId: '91',
    docType: 'WorkOrder',
    data: {
      name: 'Pump priming',
      workCenterId: '14',
      status: 'open',
      startDate: '2026-07-22',
      endDate: '2026-08-01',
    },
  },
  {
    docId: '92',
    docType: 'WorkOrder',
    data: {
      name: 'Filter swap',
      workCenterId: '14',
      status: 'open',
      startDate: '2026-08-10',
      endDate: '2026-08-21',
    },
  },
  {
    docId: '93',
    docType: 'WorkOrder',
    data: {
      name: 'Drive test',
      workCenterId: '15',
      status: 'complete',
      startDate: '2026-03-08',
      endDate: '2026-03-17',
    },
  },
  {
    docId: '94',
    docType: 'WorkOrder',
    data: {
      name: 'Enclosure assembly',
      workCenterId: '15',
      status: 'complete',
      startDate: '2026-04-03',
      endDate: '2026-04-11',
    },
  },
  {
    docId: '95',
    docType: 'WorkOrder',
    data: {
      name: 'Label run',
      workCenterId: '15',
      status: 'complete',
      startDate: '2026-04-20',
      endDate: '2026-04-23',
    },
  },
  {
    docId: '96',
    docType: 'WorkOrder',
    data: {
      name: 'Crate build',
      workCenterId: '15',
      status: 'complete',
      startDate: '2026-05-06',
      endDate: '2026-05-11',
    },
  },
  {
    docId: '97',
    docType: 'WorkOrder',
    data: {
      name: 'Frame assembly',
      workCenterId: '15',
      status: 'complete',
      startDate: '2026-05-31',
      endDate: '2026-06-07',
    },
  },
  {
    docId: '98',
    docType: 'WorkOrder',
    data: {
      name: 'Wiring harness build',
      workCenterId: '15',
      status: 'open',
      startDate: '2026-06-12',
      endDate: '2026-06-16',
    },
  },
  {
    docId: '99',
    docType: 'WorkOrder',
    data: {
      name: 'QA sample inspection',
      workCenterId: '15',
      status: 'open',
      startDate: '2026-06-30',
      endDate: '2026-07-03',
    },
  },
  {
    docId: '100',
    docType: 'WorkOrder',
    data: {
      name: 'Tooling retrofit',
      workCenterId: '15',
      status: 'open',
      startDate: '2026-07-23',
      endDate: '2026-07-28',
    },
  },
  {
    docId: '101',
    docType: 'WorkOrder',
    data: {
      name: 'Pallet restock',
      workCenterId: '15',
      status: 'open',
      startDate: '2026-08-08',
      endDate: '2026-08-14',
    },
  },
  {
    docId: '102',
    docType: 'WorkOrder',
    data: {
      name: 'Line recommission',
      workCenterId: '15',
      status: 'open',
      startDate: '2026-08-26',
      endDate: '2026-09-06',
    },
  },
  {
    docId: '103',
    docType: 'WorkOrder',
    data: {
      name: 'Rush rework',
      workCenterId: '1',
      status: 'blocked',
      startDate: '2026-06-06',
      endDate: '2026-06-12',
    },
  },
  {
    docId: '104',
    docType: 'WorkOrder',
    data: {
      name: 'Expedite order',
      workCenterId: '1',
      status: 'in-progress',
      startDate: '2026-06-08',
      endDate: '2026-06-12',
    },
  },
  {
    docId: '105',
    docType: 'WorkOrder',
    data: {
      name: 'Parallel build A',
      workCenterId: '5',
      status: 'open',
      startDate: '2026-06-11',
      endDate: '2026-06-18',
    },
  },
  {
    docId: '106',
    docType: 'WorkOrder',
    data: {
      name: 'Parallel build B',
      workCenterId: '5',
      status: 'open',
      startDate: '2026-06-13',
      endDate: '2026-06-18',
    },
  },
  {
    docId: '107',
    docType: 'WorkOrder',
    data: {
      name: 'Overlap audit',
      workCenterId: '9',
      status: 'blocked',
      startDate: '2026-06-02',
      endDate: '2026-06-10',
    },
  },
  {
    docId: '108',
    docType: 'WorkOrder',
    data: {
      name: 'Overlap retest',
      workCenterId: '9',
      status: 'blocked',
      startDate: '2026-06-05',
      endDate: '2026-06-11',
    },
  },
];

/** Build the initial, fully-populated mock ERP state. */
export const createInitialMockErpState = (): MockErpState => ({
  centers,
  orders,
});
